name: Push new release

on:
  push:
    branches: 
      main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch rev number
      - name: Get rev number
        id: get-rev
        run: |
          echo "::set-output name=REV::$(git rev-list HEAD --count)"
      
      # Create tag
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{ steps.get-rev.outputs.REV }}
