name: Push new tag

on:
  push:
    branches: 
      main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Fetch rev number
      - name: Get rev number
        id: get-rev
        run: |
          echo "::set-output name=REV::$(git rev-list HEAD --count)"

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.get-rev.outputs.REV }}',
              sha: context.sha
            })
